Repository TeamSteam-11/TeamSteam, pull requests merged in 2023-08, with the labels that each got.

#210 Fix/209
  src/main/java/com/ll/TeamSteam/domain/matching/repository/MatchingRepository.java
  src/main/java/com/ll/TeamSteam/domain/matching/service/MatchingService.java
  src/main/java/com/ll/TeamSteam/domain/matchingPartner/repository/MatchingPartnerRepository.java
  src/main/java/com/ll/TeamSteam/domain/matchingPartner/service/MatchingPartnerService.java
  src/test/java/com/ll/TeamSteam/domain/recentlyUser/service/RecentlyUserServiceTest.java
Labels: 📝testcode

#207 Ref/197 매칭 관련 코드 리팩토링 및 TestCode 작성
  src/main/java/com/ll/TeamSteam/domain/home/HomeController.java
  src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java
  src/main/java/com/ll/TeamSteam/domain/matching/entity/CreateForm.java
  src/main/java/com/ll/TeamSteam/domain/matching/entity/Matching.java
  src/main/java/com/ll/TeamSteam/domain/matching/service/MatchingService.java
  src/test/java/com/ll/TeamSteam/domain/matching/controller/MatchingControllerTest.java
Labels: 🛠refactoring, 📝testcode

#211 security config 수정
  spy.log
  src/main/java/com/ll/TeamSteam/TeamSteamApplication.java
  src/main/java/com/ll/TeamSteam/global/security/SecurityConfig.java
  src/test/java/com/ll/TeamSteam/domain/recentlyUser/service/RecentlyUserServiceTest.java
  src/test/java/com/ll/TeamSteam/domain/user/controller/UserControllerTest.java
Labels: 🛠refactoring, 📝testcode

#212 TS-4 Dm 구현
  src/main/generated/com/ll/TeamSteam/domain/dm/entity/QDm.java
  src/main/generated/com/ll/TeamSteam/domain/dmMessage/entity/QDmMessage.java
  src/main/generated/com/ll/TeamSteam/domain/dmUser/entity/QDmUser.java
  src/main/java/com/ll/TeamSteam/domain/dm/controller/DmController.java
  src/main/java/com/ll/TeamSteam/domain/dm/dto/DmDto.java
  src/main/java/com/ll/TeamSteam/domain/dm/entity/Dm.java
  src/main/java/com/ll/TeamSteam/domain/dm/exception/NoDmException.java
  src/main/java/com/ll/TeamSteam/domain/dm/repository/DmRepository.java
  src/main/java/com/ll/TeamSteam/domain/dm/service/DmService.java
  src/main/java/com/ll/TeamSteam/domain/dmMessage/controller/DmMessageController.java
  src/main/java/com/ll/TeamSteam/domain/dmMessage/dto/DmMessageDto.java
  src/main/java/com/ll/TeamSteam/domain/dmMessage/dto/request/DmMessageRequest.java
  src/main/java/com/ll/TeamSteam/domain/dmMessage/dto/response/DmResponse.java
  src/main/java/com/ll/TeamSteam/domain/dmMessage/dto/response/DmSignalType.java
  src/main/java/com/ll/TeamSteam/domain/dmMessage/entity/DmMessage.java
  src/main/java/com/ll/TeamSteam/domain/dmMessage/repository/DmMessageRepository.java
  src/main/java/com/ll/TeamSteam/domain/dmMessage/service/DmMessageService.java
  src/main/java/com/ll/TeamSteam/domain/dmUser/entity/DmUser.java
  src/main/java/com/ll/TeamSteam/domain/dmUser/repository/DmUserRepository.java
  src/main/java/com/ll/TeamSteam/domain/dmUser/service/DmUserService.java
  src/main/java/com/ll/TeamSteam/global/error/GlobalExceptionHandler.java
  src/main/resources/static/dm.js
  src/main/resources/templates/dm/dmRoom.html
  src/main/resources/templates/user/profile.html
Labels: 🎉feature

#213 TS-9 매칭 관련 테스트코드 추가
  src/test/java/com/ll/TeamSteam/domain/matching/service/MatchingServiceTest.java
Labels: 📝testcode

#215 TS-13 DM 테스트코드 작성
  src/main/java/com/ll/TeamSteam/domain/dm/controller/DmController.java
  src/main/java/com/ll/TeamSteam/domain/dm/service/DmService.java
  src/test/java/com/ll/TeamSteam/domain/chatRoom/controller/ChatRoomControllerTest.java
  src/test/java/com/ll/TeamSteam/domain/chatRoom/service/ChatRoomServiceTest.java
  src/test/java/com/ll/TeamSteam/domain/dm/service/DmServiceTest.java
Labels: 📝testcode

#216 TS-12 dockerCompose
  build.gradle
  docker-compose.yml
  prometheus.yml
Labels: 🎉feature

#217 Ts 18
  docker-compose.yml
  src/main/resources/application-prod.yml
Labels: 🎉feature

#218 ref : target 주소 수정
  prometheus.yml
Labels: 🛠refactoring

#219 TS-20 docker-compose.yml 수정
  docker-compose.yml
Labels: 🛠refactoring

#220 TS-23 프로메테우스 수정
  docker-compose.yml
Labels: 🐞bug

#221 TS-24 yml 설정 변경
  docker-compose.yml
Labels: 🛠refactoring

#222 TS-22 매칭 등록 폼 UI 수정
  src/main/java/com/ll/TeamSteam/domain/matching/entity/CreateForm.java
  src/test/java/com/ll/TeamSteam/domain/matching/controller/MatchingControllerTest.java
Labels: 🛠refactoring

#224 TS-8 로그인 버그 수정
  src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java
Labels: 🐞bug

#225 TS-25 mongoDB 적용 후 chat 버그 수정
  src/main/java/com/ll/TeamSteam/domain/chatMessage/dto/ChatMessageDto.java
  src/main/java/com/ll/TeamSteam/domain/chatMessage/entity/ChatMessage.java
  src/main/java/com/ll/TeamSteam/domain/chatMessage/service/ChatMessageService.java
  src/main/java/com/ll/TeamSteam/domain/user/service/UserService.java
Labels: 🐞bug
