Repository TeamSteam-11/TeamSteam, pull requests merged in 2023-06, with the labels that each got.

#8 Feature/5 Navbar 임시 적용
  src/main/java/com/ll/TeamSteam/TeamSteamApplication.java
  src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java
  src/main/java/com/ll/TeamSteam/domain/matching/entity/Matching.java
  src/main/resources/static/resource/common.css
  src/main/resources/static/resource/common.js
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/matching/list.html
Labels: feature

#9 Feature/3
  .gitignore
  build.gradle
  src/main/java/com/ll/TeamSteam/TeamSteamApplication.java
  src/main/java/com/ll/TeamSteam/domain/user/controller/SteamLoginController.java
  src/main/java/com/ll/TeamSteam/domain/user/entity/User.java
  src/main/java/com/ll/TeamSteam/global/baseEntity/BaseEntity.java
  src/main/java/com/ll/TeamSteam/global/security/SecurityConfig.java
  src/main/java/com/ll/TeamSteam/global/security/SecurityUser.java
  src/main/java/com/ll/TeamSteam/global/security/SecurityUserAdapter.java
  src/main/resources/application.yml
  src/main/resources/templates/login.html
Labels: feature

#11 feat : SteamLogin 확인, p6spy 추가
  src/main/java/com/ll/TeamSteam/domain/home/HomeController.java
  src/main/java/com/ll/TeamSteam/domain/user/controller/SteamLoginController.java
  src/main/java/com/ll/TeamSteam/domain/user/repository/UserRepository.java
  src/main/java/com/ll/TeamSteam/domain/user/service/UserService.java
  src/main/java/com/ll/TeamSteam/global/p6spy/P6SpySqlFormatter.java
  src/main/java/com/ll/TeamSteam/global/rq/Rq.java
  src/main/java/com/ll/TeamSteam/global/rsdata/RsData.java
  src/main/java/com/ll/TeamSteam/global/security/SecurityConfig.java
  src/main/java/com/ll/TeamSteam/standard/Ut.java
  src/main/resources/templates/main/home.html
  src/main/resources/templates/user/isLogin.html
  src/main/resources/templates/user/login.html
Labels: feature

#12 Feature/7 매칭 등록 페이지 생성
  src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java
  src/main/java/com/ll/TeamSteam/domain/matching/entity/Matching.java
  src/main/java/com/ll/TeamSteam/domain/matching/repository/MatchingRepository.java
  src/main/java/com/ll/TeamSteam/domain/matching/service/MatchingService.java
  src/main/java/com/ll/TeamSteam/global/rq/Rq.java
  src/main/java/com/ll/TeamSteam/global/rsData/RsData.java
  src/main/java/com/ll/TeamSteam/standard/util/Ut.java
  src/main/resources/templates/matching/create.html
  src/main/resources/templates/matching/list.html
Labels: 🎉feature

#15 Feature/6 유저 로그인 시 데이터 DB에 등록
  src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java
  src/main/java/com/ll/TeamSteam/domain/user/entity/User.java
  src/main/java/com/ll/TeamSteam/domain/user/repository/UserRepository.java
  src/main/java/com/ll/TeamSteam/domain/user/service/UserService.java
  src/main/java/com/ll/TeamSteam/global/security/SecurityConfig.java
  src/main/java/com/ll/TeamSteam/global/security/SteamClient.java
  src/main/java/com/ll/TeamSteam/global/security/SteamClientImpl.java
  src/main/java/com/ll/TeamSteam/global/security/UserInfoResponse.java
  src/main/resources/templates/main/main.html
Labels: 🎉feature

#17 bug/17 rsdata 디렉터리 rsData로 수정
  src/main/java/com/ll/TeamSteam/global/rq/Rq.java
  src/main/java/com/ll/TeamSteam/global/rsData/RsData.java
  src/main/java/com/ll/TeamSteam/global/rsdata/RsData.java
  src/main/resources/application-secret.yml.default
Labels: 🐞bug, 🎠chore

#18 chore : 쓸모없는 import문 제거
  src/main/java/com/ll/TeamSteam/domain/home/HomeController.java
Labels: 🎠chore

#21 Feature/20
  src/main/java/com/ll/TeamSteam/TeamSteamApplication.java
  src/main/java/com/ll/TeamSteam/domain/matchingTag/entity/GenreTagType.java
  src/main/java/com/ll/TeamSteam/domain/steam/controller/SteamController.java
  src/main/java/com/ll/TeamSteam/domain/steam/service/SteamService.java
  src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java
  src/main/java/com/ll/TeamSteam/domain/user/entity/Gender.java
  src/main/java/com/ll/TeamSteam/domain/user/entity/User.java
  src/main/java/com/ll/TeamSteam/domain/user/service/UserService.java
  src/main/java/com/ll/TeamSteam/domain/userTag/entity/userTag.java
  src/main/java/com/ll/TeamSteam/global/rq/Rq.java
  src/main/java/com/ll/TeamSteam/global/security/SecurityUser.java
  src/main/java/com/ll/TeamSteam/global/security/SteamClient.java
  src/main/java/com/ll/TeamSteam/global/security/SteamClientImpl.java
  src/main/java/com/ll/TeamSteam/global/security/UserInfoResponse.java
  src/main/resources/templates/user/createGenre.html
Labels: 🎉feature, 🛠refactoring

#24 ref : 시큐리티유저적용
  src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java
  src/main/java/com/ll/TeamSteam/global/security/SecurityUser.java
Labels: 🛠refactoring

#25 feat/4 ChatMessage 병합
  src/main/java/com/ll/TeamSteam/domain/chatMessage/controller/ChatMessageController.java
  src/main/java/com/ll/TeamSteam/domain/chatMessage/dto/ChatMessageDto.java
  src/main/java/com/ll/TeamSteam/domain/chatMessage/dto/request/ChatMessageRequest.java
  src/main/java/com/ll/TeamSteam/domain/chatMessage/dto/response/SignalResponse.java
  src/main/java/com/ll/TeamSteam/domain/chatMessage/dto/response/SignalType.java
  src/main/java/com/ll/TeamSteam/domain/chatMessage/entity/ChatMessage.java
  src/main/java/com/ll/TeamSteam/domain/chatMessage/repository/ChatMessageRepository.java
  src/main/java/com/ll/TeamSteam/domain/chatMessage/service/ChatMessageService.java
  src/main/java/com/ll/TeamSteam/domain/chatRoom/controller/ChatRoomController.java
  src/main/java/com/ll/TeamSteam/domain/chatRoom/dto/ChatRoomDto.java
  src/main/java/com/ll/TeamSteam/domain/chatRoom/dto/RoomCreateRequest.java
  src/main/java/com/ll/TeamSteam/domain/chatRoom/entity/ChatRoom.java
  src/main/java/com/ll/TeamSteam/domain/chatRoom/repository/ChatRoomRepository.java
  src/main/java/com/ll/TeamSteam/domain/chatRoom/service/ChatRoomService.java
  src/main/java/com/ll/TeamSteam/domain/chatUser/entity/ChatUser.java
  src/main/java/com/ll/TeamSteam/domain/chatUser/entity/ChatUserType.java
  src/main/java/com/ll/TeamSteam/domain/chatUser/repository/ChatUserRepository.java
  src/main/java/com/ll/TeamSteam/domain/chatUser/service/ChatUserService.java
  src/main/java/com/ll/TeamSteam/domain/user/dto/UserDto.java
  src/main/java/com/ll/TeamSteam/domain/user/service/UserService.java
  src/main/java/com/ll/TeamSteam/global/config/WebSocketConfig.java
  src/main/java/com/ll/TeamSteam/global/config/WebSocketSecurityConfig.java
  src/main/java/com/ll/TeamSteam/global/init/NotProd.java
  src/main/java/com/ll/TeamSteam/global/rq/Rq.java
  src/main/resources/static/app.js
  src/main/resources/static/resource/common.css
  src/main/resources/static/resource/common.js
  src/main/resources/static/resource/common/common.css
  src/main/resources/static/resource/common/common.js
  src/main/resources/static/style.css
  src/main/resources/templates/chat/room.html
  src/main/resources/templates/chat/rooms.html
  src/main/resources/templates/chat/userList.html
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/main/home.html
Labels: 🎉feature

#28 bug/27 EnterMessageBug
  src/main/java/com/ll/TeamSteam/domain/chatUser/entity/ChatUser.java
  src/main/java/com/ll/TeamSteam/domain/matching/service/MatchingService.java
  src/main/java/com/ll/TeamSteam/global/init/NotProd.java
  src/main/resources/templates/chat/room.html
Labels: 🐞bug

#33 Feature/32 초대 기능 구체화 및 수락/거절 로직 구현
  src/main/java/com/ll/TeamSteam/domain/chatRoom/controller/ChatRoomController.java
  src/main/java/com/ll/TeamSteam/domain/chatRoom/service/ChatRoomService.java
  src/main/java/com/ll/TeamSteam/domain/notification/controller/NotificationController.java
  src/main/java/com/ll/TeamSteam/domain/notification/entity/Notification.java
  src/main/java/com/ll/TeamSteam/domain/notification/eventListener/NotificationEventListener.java
  src/main/java/com/ll/TeamSteam/domain/notification/repository/NotificationRepository.java
  src/main/java/com/ll/TeamSteam/domain/notification/service/NotificationService.java
  src/main/java/com/ll/TeamSteam/domain/user/repository/UserRepository.java
  src/main/java/com/ll/TeamSteam/global/event/EventAfterInvite.java
  src/main/java/com/ll/TeamSteam/global/init/NotProd.java
  src/main/java/com/ll/TeamSteam/global/rq/Rq.java
  src/main/java/com/ll/TeamSteam/standard/Ut.java
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/main/home.html
  src/main/resources/templates/notification/list.html
Labels: 🎉feature
