Repository TeamSteam-11/TeamSteam, pull requests merged in 2023-09, with the labels that each got.

#228 TS-33 recentlyUser 버그 2차 수정
  src/main/java/com/ll/TeamSteam/domain/recentlyUser/repository/RecentlyUserRepository.java
  src/main/java/com/ll/TeamSteam/domain/recentlyUser/service/RecentlyUserService.java
  src/test/java/com/ll/TeamSteam/domain/recentlyUser/service/RecentlyUserServiceTest.java
Labels: 🐞bug

#229 TS-35 matching mic 항목 추가
  src/main/generated/com/ll/TeamSteam/domain/matching/entity/QMatching.java
  src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java
  src/main/java/com/ll/TeamSteam/domain/matching/entity/CreateForm.java
  src/main/java/com/ll/TeamSteam/domain/matching/entity/Matching.java
  src/main/java/com/ll/TeamSteam/domain/matching/service/MatchingService.java
  src/main/java/com/ll/TeamSteam/global/init/NotProd.java
  src/main/resources/templates/matching/create.html
  src/main/resources/templates/matching/detail.html
  src/main/resources/templates/matching/modify.html
  src/test/java/com/ll/TeamSteam/domain/chatRoom/service/ChatRoomServiceTest.java
  src/test/java/com/ll/TeamSteam/domain/matching/service/MatchingServiceTest.java
Labels: 🎉feature

#230 TS-31 네비바,main태그 너비 및 디자인 수정
  src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java
  src/main/resources/static/layout.css
  src/main/resources/static/resource/common/TSDog.png
  src/main/resources/static/resource/common/common.css
  src/main/resources/static/style.css
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/matching/list.html
Labels: 🖼design

#231 TS-29 글쓴이 필터 추가, chatMessage 시간 버그 수정
  src/main/java/com/ll/TeamSteam/domain/home/HomeController.java
  src/main/java/com/ll/TeamSteam/domain/matching/repository/MatchingRepository.java
  src/main/java/com/ll/TeamSteam/domain/matching/service/MatchingService.java
  src/main/resources/static/app.js
  src/main/resources/templates/chat/userList.html
  src/main/resources/templates/main/home.html
  src/main/resources/templates/matching/detail.html
  src/main/resources/templates/matching/list.html
Labels: 🐞bug, 🎉feature

#233 Ts-39 네비바 우측 아이콘 수정
  src/main/resources/static/layout.css
  src/main/resources/templates/common/layout.html
Labels: 🖼design

#232 TS-40 notification 페이지 구현
  src/main/java/com/ll/TeamSteam/domain/chatRoom/controller/ChatRoomController.java
  src/main/java/com/ll/TeamSteam/domain/chatRoom/service/ChatRoomService.java
  src/main/java/com/ll/TeamSteam/domain/chatUser/repository/ChatUserRepository.java
  src/main/java/com/ll/TeamSteam/domain/chatUser/service/ChatUserService.java
  src/main/java/com/ll/TeamSteam/domain/dm/controller/DmController.java
  src/main/java/com/ll/TeamSteam/domain/dm/repository/DmRepository.java
  src/main/java/com/ll/TeamSteam/domain/dm/service/DmService.java
  src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java
  src/main/java/com/ll/TeamSteam/domain/notification/controller/NotificationController.java
  src/main/java/com/ll/TeamSteam/domain/notification/repository/NotificationRepository.java
  src/main/java/com/ll/TeamSteam/domain/notification/service/NotificationService.java
  src/main/resources/templates/chat/chatList.html
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/dm/dmList.html
  src/main/resources/templates/matching/list.html
  src/main/resources/templates/notification/list.html
Labels: 🐞bug, 🎉feature

#234 TS-16 생성 시 알림 기능 추가 및 채팅 목록 버그 수정
  src/main/generated/com/ll/TeamSteam/domain/notification/entity/QNotification.java
  src/main/java/com/ll/TeamSteam/domain/chatRoom/controller/ChatRoomController.java
  src/main/java/com/ll/TeamSteam/domain/chatRoom/service/ChatRoomService.java
  src/main/java/com/ll/TeamSteam/domain/dm/controller/DmController.java
  src/main/java/com/ll/TeamSteam/domain/dm/service/DmService.java
  src/main/java/com/ll/TeamSteam/domain/notification/controller/NotificationController.java
  src/main/java/com/ll/TeamSteam/domain/notification/entity/Notification.java
  src/main/java/com/ll/TeamSteam/domain/notification/eventListener/NotificationEventListener.java
  src/main/java/com/ll/TeamSteam/domain/notification/service/NotificationService.java
  src/main/java/com/ll/TeamSteam/global/event/EventAfterCreateDm.java
  src/main/java/com/ll/TeamSteam/global/event/EventEnterNewChatUser.java
  src/main/resources/templates/chat/chatList.html
  src/main/resources/templates/dm/dmList.html
  src/main/resources/templates/notification/list.html
Labels: 🐞bug, 🎉feature

#235 TS-41 채팅방 입장 시 중복으로 알림 발생하는 버그 수정
  src/main/java/com/ll/TeamSteam/domain/chatRoom/service/ChatRoomService.java
Labels: 🐞bug

#236 Ts-38 명예의전당 페이지 내순위 출력, 디자인 변경
  src/main/java/com/ll/TeamSteam/domain/rank/controller/RankController.java
  src/main/java/com/ll/TeamSteam/domain/rank/service/RankService.java
  src/main/java/com/ll/TeamSteam/domain/user/repository/UserRepository.java
  src/main/resources/templates/rank/rank.html
Labels: 🎉feature, 🖼design

#238 TS-42 home UI 수정
  src/main/java/com/ll/TeamSteam/domain/home/HomeController.java
  src/main/java/com/ll/TeamSteam/domain/matching/service/MatchingService.java
  src/main/resources/static/resource/common/logo.png
  src/main/resources/templates/main/home.html
Labels: 🛠refactoring, 🖼design

#240 TS-36 프로필 UI 수정
  src/main/java/com/ll/TeamSteam/domain/steam/service/SteamGameLibraryService.java
  src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java
  src/main/resources/static/layout.css
  src/main/resources/templates/user/profile.html
Labels: 🎉feature, 🖼design

#237 TS-37 매칭 UI 디자인
  src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java
  src/main/java/com/ll/TeamSteam/domain/matching/entity/CreateForm.java
  src/main/java/com/ll/TeamSteam/domain/matching/entity/Matching.java
  src/main/java/com/ll/TeamSteam/domain/matching/service/MatchingService.java
  src/main/resources/templates/matching/create.html
  src/main/resources/templates/matching/detail.html
  src/main/resources/templates/matching/list.html
  src/main/resources/templates/matching/modify.html
  src/test/java/com/ll/TeamSteam/domain/matching/service/MatchingServiceTest.java
Labels: 🖼design

#242 TS-45 home에 MIC 파싱 안되는 버그 수정
  src/main/resources/templates/main/home.html
Labels: 🐞bug

#243 TS-46 모집인원 수정
  src/main/java/com/ll/TeamSteam/domain/chatRoom/controller/ChatRoomController.java
  src/main/java/com/ll/TeamSteam/domain/dm/controller/DmController.java
  src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java
Labels: 🛠refactoring

#244 TS-48 디자인 종합적인 수정, 채팅 메시지 글자 수 제한
  src/main/java/com/ll/TeamSteam/domain/chatMessage/dto/ChatMessageDto.java
  src/main/java/com/ll/TeamSteam/domain/chatMessage/entity/ChatMessage.java
  src/main/java/com/ll/TeamSteam/domain/chatMessage/error/ChatMessageOverContent.java
  src/main/java/com/ll/TeamSteam/domain/chatMessage/service/ChatMessageService.java
  src/main/java/com/ll/TeamSteam/domain/dmMessage/entity/DmMessage.java
  src/main/java/com/ll/TeamSteam/domain/dmMessage/service/DmMessageService.java
  src/main/java/com/ll/TeamSteam/domain/miniGame/repository/MiniGameRepository.java
  src/main/java/com/ll/TeamSteam/domain/miniGame/service/MiniGameService.java
  src/main/java/com/ll/TeamSteam/global/error/GlobalExceptionHandler.java
  src/main/resources/static/layout.css
  src/main/resources/static/minigame/style/minigame.css
  src/main/resources/static/resource/common/TSDog.png
  src/main/resources/templates/chat/chatList.html
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/dm/dmList.html
  src/main/resources/templates/main/home.html
  src/main/resources/templates/matching/detail.html
  src/main/resources/templates/matching/list.html
  src/main/resources/templates/minigame/index.html
  src/main/resources/templates/user/createGameTag.html
  src/main/resources/templates/user/createGenre.html
Labels: 🐞bug, 🛠refactoring, 🖼design

#245 TS-47 프로필 버그들 수정
  src/main/resources/templates/user/profile.html
Labels: 🐞bug, 🖼design

#246 TS-49 UI 최종 버그 수정
  src/main/resources/static/resource/common/common.css
  src/main/resources/templates/matching/create.html
  src/main/resources/templates/matching/detail.html
  src/main/resources/templates/matching/list.html
  src/main/resources/templates/rank/rank.html
Labels: 🖼design

#247 TS-51 푸터 UI 작업
  src/main/resources/static/layout.css
  src/main/resources/templates/chat/chatList.html
  src/main/resources/templates/chat/inviteList.html
  src/main/resources/templates/chat/room.html
  src/main/resources/templates/chat/userList.html
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/dm/dmList.html
  src/main/resources/templates/dm/dmRoom.html
  src/main/resources/templates/error/400.html
  src/main/resources/templates/error/403.html
  src/main/resources/templates/error/404.html
  src/main/resources/templates/error/405.html
  src/main/resources/templates/error/canNotEnterChatRoom.html
  src/main/resources/templates/error/commonError.html
  src/main/resources/templates/error/kickedError.html
  src/main/resources/templates/error/noChatroomError.html
  src/main/resources/templates/error/notInChatRoom.html
  src/main/resources/templates/main/home.html
  src/main/resources/templates/matching/create.html
  src/main/resources/templates/matching/detail.html
  src/main/resources/templates/matching/list.html
  src/main/resources/templates/matching/modify.html
  src/main/resources/templates/minigame/index.html
  src/main/resources/templates/notification/list.html
  src/main/resources/templates/rank/rank.html
  src/main/resources/templates/user/createGameTag.html
  src/main/resources/templates/user/createGenre.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/profile.html
Labels: 🖼design

#241 TS-44 채팅창 UI 수정
  src/main/java/com/ll/TeamSteam/domain/chatRoom/controller/ChatRoomController.java
  src/main/resources/static/app.js
  src/main/resources/static/dm.js
  src/main/resources/templates/chat/inviteList.html
  src/main/resources/templates/chat/room.html
  src/main/resources/templates/chat/userList.html
  src/main/resources/templates/dm/dmRoom.html
Labels: 🖼design

#248 TS-52 프로필UI 최종 수정
  src/main/resources/templates/user/profile.html
Labels: 🐞bug

#249 TS-53 전체 UI 디자인 수정, 구글 애드센스 코드 추가
  src/main/resources/templates/chat/chatList.html
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/dm/dmList.html
  src/main/resources/templates/user/createGameTag.html
  src/main/resources/templates/user/createGenre.html
Labels: 🖼design

#250 design : 프로필 UI 수정, noti 아이콘 알림뱃지 수정, 스크롤바 적용
  src/main/resources/templates/chat/room.html
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/dm/dmRoom.html
  src/main/resources/templates/matching/detail.html
  src/main/resources/templates/user/profile.html
Labels: 🖼design
