Repository TeamSteam-11/TeamSteam, pull requests merged in 2023-10, with the labels that each got.

#253 TS-60 퇴장한 유저에게도 새 유저 입장 알림 발생되는 버그 수정
  src/main/java/com/ll/TeamSteam/domain/chatRoom/service/ChatRoomService.java
Labels: 🐞bug

#255 TS-57 XSS 스크립트 방어
  build.gradle
  src/main/java/com/ll/TeamSteam/domain/chatMessage/service/ChatMessageService.java
  src/main/java/com/ll/TeamSteam/domain/dmMessage/service/DmMessageService.java
  src/main/java/com/ll/TeamSteam/global/filter/CleanXss.java
  src/main/java/com/ll/TeamSteam/global/filter/CrossScriptingFilter.java
  src/main/java/com/ll/TeamSteam/global/filter/RequestWrapper.java
Labels: 🐞bug

#256 TS-61 최근 유저 매너온도 설명 드롭다운 추가
  src/main/resources/templates/user/profile.html
Labels: 🖼design

#257 TS-64 매칭 목록에서 페이지가 없을 때 다음 버튼 제거
  src/main/resources/templates/matching/list.html
Labels: 🐞bug

#258 TS-62 태그 설정에서 게임 태그 선택 시, 이전으로 이동하면 선택된 표시가 풀리는 버그 수정
  src/main/resources/templates/user/createGameTag.html
Labels: 🐞bug

#260 TS-66 입장메시지 변경
  src/main/java/com/ll/TeamSteam/domain/chatMessage/service/ChatMessageService.java
  src/main/java/com/ll/TeamSteam/global/filter/CrossScriptingFilter.java
  src/main/java/com/ll/TeamSteam/global/filter/RequestWrapper.java
Labels: 🛠refactoring

#261 TS-68 MatchingServiceTest 오류 수정
  src/test/java/com/ll/TeamSteam/domain/matching/service/MatchingServiceTest.java
Labels: 🐞bug

#262 TS-58 미니 프로필 태그 개수 5개 이하만 조회 가능
  src/main/resources/templates/matching/detail.html
  src/main/resources/templates/user/profile.html
Labels: 🖼design

#263 TS-63 친구신청 시 친구추가버튼 숨김
  src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java
  src/main/resources/templates/rank/rank.html
  src/main/resources/templates/user/profile.html
Labels: 🐞bug

#264 TS-69 unique 제약조건 추가
  src/main/java/com/ll/TeamSteam/domain/user/entity/User.java
  src/main/resources/templates/error/500.html
Labels: 🎉feature
