Repository TeamSteam-11/TeamSteam, pull requests merged in 2023-07, with the labels that each got.

#34 Feature/22 로그인 이후 유저라이브러리 데이터 입력
  src/main/java/com/ll/TeamSteam/domain/matchingTag/entity/GenreTagType.java
  src/main/java/com/ll/TeamSteam/domain/steam/service/SteamService.java
  src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java
  src/main/java/com/ll/TeamSteam/domain/user/entity/User.java
  src/main/java/com/ll/TeamSteam/domain/user/repository/UserRepository.java
  src/main/java/com/ll/TeamSteam/domain/user/service/UserService.java
  src/main/java/com/ll/TeamSteam/domain/userTag/UserTag.java
  src/main/java/com/ll/TeamSteam/domain/userTag/UserTagRepository.java
  src/main/java/com/ll/TeamSteam/domain/userTag/gameTag/GameTag.java
  src/main/java/com/ll/TeamSteam/domain/userTag/gameTag/GameTagRepository.java
  src/main/java/com/ll/TeamSteam/domain/userTag/gameTag/TagOn.java
  src/main/java/com/ll/TeamSteam/domain/userTag/genreTag/GenreTag.java
  src/main/java/com/ll/TeamSteam/domain/userTag/genreTag/GenreTagRepository.java
  src/main/resources/templates/user/createGenre.html
Labels: 🎉feature, 🛠refactoring

#36 ref/35 invite로직 리팩토링, 버그 수정
  src/main/java/com/ll/TeamSteam/domain/chatRoom/controller/ChatRoomController.java
  src/main/java/com/ll/TeamSteam/domain/chatRoom/entity/ChatRoom.java
  src/main/java/com/ll/TeamSteam/domain/chatRoom/service/ChatRoomService.java
  src/main/java/com/ll/TeamSteam/domain/notification/repository/NotificationRepository.java
  src/main/java/com/ll/TeamSteam/domain/notification/service/NotificationService.java
  src/main/java/com/ll/TeamSteam/domain/user/dto/UserDto.java
  src/main/java/com/ll/TeamSteam/domain/user/service/UserService.java
  src/main/resources/static/app.js
  src/main/resources/templates/chat/inviteList.html
Labels: 🐞bug, 🛠refactoring

#38 ref/37 중복 초대 안되도록 로직 변경
  src/main/java/com/ll/TeamSteam/domain/chatRoom/entity/ChatRoom.java
  src/main/java/com/ll/TeamSteam/domain/chatRoom/service/ChatRoomService.java
  src/main/java/com/ll/TeamSteam/domain/notification/repository/NotificationRepository.java
  src/main/java/com/ll/TeamSteam/domain/notification/service/NotificationService.java
  src/main/resources/templates/chat/inviteList.html
Labels: 🛠refactoring

#40 Feature/26 게임라이브러리분리, 이미지추가
  src/main/java/com/ll/TeamSteam/domain/steam/entity/SteamGameLibrary.java
  src/main/java/com/ll/TeamSteam/domain/steam/repository/SteamGameLibraryRepository.java
  src/main/java/com/ll/TeamSteam/domain/steam/service/SteamService.java
  src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java
  src/main/java/com/ll/TeamSteam/domain/user/entity/User.java
  src/main/java/com/ll/TeamSteam/domain/user/service/UserService.java
  src/main/java/com/ll/TeamSteam/domain/userTag/gameTag/GameTag.java
  src/main/java/com/ll/TeamSteam/domain/userTag/gameTag/TagOn.java
  src/main/resources/application.yml
  src/main/resources/templates/user/profile.html
Labels: 🎉feature, 🛠refactoring

#42 Feature/14 매칭 등록 기능 추가 및 목록 페이지 구현
  src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java
  src/main/java/com/ll/TeamSteam/domain/matching/entity/Matching.java
  src/main/java/com/ll/TeamSteam/domain/matching/repository/MatchingRepository.java
  src/main/java/com/ll/TeamSteam/domain/matching/service/MatchingService.java
  src/main/java/com/ll/TeamSteam/global/init/NotProd.java
  src/main/resources/templates/main/home.html
  src/main/resources/templates/matching/create.html
  src/main/resources/templates/matching/detail.html
  src/main/resources/templates/matching/list.html
Labels: 🎉feature

#41 feat : 토스트 알림 적용
  src/main/java/com/ll/TeamSteam/domain/chatRoom/controller/ChatRoomController.java
  src/main/java/com/ll/TeamSteam/domain/chatRoom/service/ChatRoomService.java
  src/main/resources/templates/chat/inviteList.html
Labels: 🎉feature

#51 Bug/50 채팅 줄바꿈 오류 수정
  src/main/resources/templates/chat/room.html
Labels: 🐞bug

#52 Feature/44 게임태그 추가기능
  src/main/java/com/ll/TeamSteam/domain/steam/entity/SteamGameLibrary.java
  src/main/java/com/ll/TeamSteam/domain/steam/repository/SteamGameLibraryRepository.java
  src/main/java/com/ll/TeamSteam/domain/steam/service/SteamService.java
  src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java
  src/main/java/com/ll/TeamSteam/domain/user/service/UserService.java
  src/main/java/com/ll/TeamSteam/domain/userTag/gameTag/GameTag.java
  src/main/resources/templates/user/createGameTag.html
  src/main/resources/templates/user/profile.html
Labels: 🎉feature, 🛠refactoring

#55 chore/54 쓸모없는 import 문 삭제 및 잘못 추가된 파일 삭제
  q
Labels: 🎠chore

#56 Feature/45 좋아요 싫어요, 친구목록 추가
  src/main/java/com/ll/TeamSteam/domain/friend/entity/Friend.java
  src/main/java/com/ll/TeamSteam/domain/friend/repository/FriendRepository.java
  src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java
  src/main/java/com/ll/TeamSteam/domain/user/entity/User.java
  src/main/java/com/ll/TeamSteam/domain/user/service/UserService.java
  src/main/java/com/ll/TeamSteam/global/init/NotProd.java
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/user/frendsList.html
  src/main/resources/templates/user/profile.html
Labels: 🎉feature

#60 ref/59 매칭 글 수정, orphanRemoval 설정
  src/main/java/com/ll/TeamSteam/domain/chatRoom/entity/ChatRoom.java
  src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java
  src/main/java/com/ll/TeamSteam/domain/matching/entity/Matching.java
  src/main/java/com/ll/TeamSteam/domain/matching/service/MatchingService.java
  src/main/resources/application-prod.yml
  src/main/resources/templates/matching/detail.html
  src/main/resources/templates/matching/modify.html
Labels: 🐞bug, 🛠refactoring

#64 refactor : 배포환경 링크추가
  src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java
  src/main/resources/templates/user/login.html
Labels: 🛠refactoring

#67 Feature/57
  src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java
  src/main/java/com/ll/TeamSteam/domain/user/service/UserService.java
  src/main/java/com/ll/TeamSteam/domain/userTag/genreTag/GenreTag.java
  src/main/resources/templates/user/frendsList.html
  src/main/resources/templates/user/profile.html
Labels: 🎉feature, 🖼design

#69 bug/68 redirect url 수정
  src/main/java/com/ll/TeamSteam/domain/chatRoom/controller/ChatRoomController.java
Labels: 🐞bug

#73 feat/70 매칭 게임,장르태그 추가, 이미지 추가
  src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java
  src/main/java/com/ll/TeamSteam/domain/matching/entity/Matching.java
  src/main/java/com/ll/TeamSteam/domain/matching/service/MatchingService.java
  src/main/java/com/ll/TeamSteam/domain/matchingTag/entity/MatchingTag.java
  src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java
  src/main/java/com/ll/TeamSteam/domain/user/service/UserService.java
  src/main/java/com/ll/TeamSteam/global/init/NotProd.java
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/matching/create.html
  src/main/resources/templates/matching/list.html
Labels: 🎉feature, 🖼design

#76 Bug/75 ActiveProfile test 추가
  src/test/java/com/ll/TeamSteam/TeamSteamApplicationTests.java
Labels: 🐞bug

#79 dockerfile 생성
  Dockerfile
Labels: 🎉feature

#74 Design/58 매칭 UI 수정
  src/main/resources/static/resource/common/common.css
  src/main/resources/templates/matching/create.html
  src/main/resources/templates/matching/detail.html
  src/main/resources/templates/matching/list.html
  src/main/resources/templates/matching/modify.html
Labels: 🖼design

#82 Feature/78 마이프로필 수정
  src/main/java/com/ll/TeamSteam/domain/steam/repository/SteamGameLibraryRepository.java
  src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java
  src/main/java/com/ll/TeamSteam/domain/user/service/UserService.java
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/user/profile.html
Labels: 🎉feature, 🛠refactoring

#81 Refactoring/80 로그인UI 적용 및 baseUrl 적용
  Dockerfile
  src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/static/resource/common/common.css
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/user/login.html
Labels: 🛠refactoring, 🖼design, 💣conflict

#85 Bug/84 로그인 URL 경로 수정
  src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java
Labels: 🐞bug

#88 Ref/83 매칭 수정 기능 리팩토링
  src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java
  src/main/java/com/ll/TeamSteam/domain/matching/entity/Matching.java
  src/main/java/com/ll/TeamSteam/domain/matching/service/MatchingService.java
  src/main/resources/templates/matching/modify.html
Labels: 🛠refactoring

#90 Design/86 마이페이지UI수정, 레이아웃에 프로필추가
  src/main/java/com/ll/TeamSteam/global/security/UserInfoResponse.java
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/user/profile.html
Labels: 🐞bug, 🖼design

#91 Feature/89 매칭 파트너 부분 구현
  src/main/java/com/ll/TeamSteam/domain/chatRoom/service/ChatRoomService.java
  src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java
  src/main/java/com/ll/TeamSteam/domain/matchingPartner/controller/MatchingPartnerController.java
  src/main/java/com/ll/TeamSteam/domain/matchingPartner/entity/MatchingPartner.java
  src/main/java/com/ll/TeamSteam/domain/matchingPartner/repository/MatchingPartnerRepository.java
  src/main/java/com/ll/TeamSteam/domain/matchingPartner/service/MatchingPartnerService.java
  src/main/java/com/ll/TeamSteam/domain/recentlyUser/entity/RecentlyUser.java
  src/main/java/com/ll/TeamSteam/domain/user/entity/User.java
  src/main/java/com/ll/TeamSteam/global/baseEntity/BaseEntity.java
  src/main/resources/templates/matching/create.html
  src/main/resources/templates/matching/detail.html
  src/main/resources/templates/matching/modify.html
Labels: 🎉feature, 🖼design

#92 Feature/87 친구신청을 통한 알림생성
  src/main/java/com/ll/TeamSteam/domain/notification/controller/NotificationController.java
  src/main/java/com/ll/TeamSteam/domain/notification/eventListener/NotificationEventListenerFriendAdd.java
  src/main/java/com/ll/TeamSteam/domain/notification/service/NotificationService.java
  src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java
  src/main/java/com/ll/TeamSteam/domain/user/service/UserService.java
  src/main/java/com/ll/TeamSteam/global/event/EventAfterFriendAdd.java
  src/main/java/com/ll/TeamSteam/global/init/NotProd.java
Labels: 🎉feature

#98 Feature/93 확인된 버그 수정, 프로필사진 업데이트 추가
  src/main/java/com/ll/TeamSteam/domain/notification/controller/NotificationController.java
  src/main/java/com/ll/TeamSteam/domain/notification/repository/NotificationRepository.java
  src/main/java/com/ll/TeamSteam/domain/notification/service/NotificationService.java
  src/main/java/com/ll/TeamSteam/domain/steam/repository/SteamGameLibraryRepository.java
  src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java
  src/main/java/com/ll/TeamSteam/domain/user/entity/User.java
  src/main/java/com/ll/TeamSteam/domain/user/service/UserService.java
  src/main/java/com/ll/TeamSteam/domain/userTag/gameTag/GameTagRepository.java
Labels: 🐞bug, 🎉feature

#99 design : 프로필 UI 수정, 장르태그 모두 추가
  src/main/java/com/ll/TeamSteam/domain/steam/service/SteamService.java
  src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java
  src/main/resources/templates/user/createGenre.html
  src/main/resources/templates/user/profile.html
Labels: 🎉feature, 🖼design

#101 Design/97 검색창 추가 및 홈화면 배너 수정
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/main/home.html
  src/main/resources/templates/matching/list.html
Labels: 🖼design

#104 feat/103 제목 검색
  src/main/java/com/ll/TeamSteam/domain/chatRoom/controller/ChatRoomController.java
  src/main/java/com/ll/TeamSteam/domain/chatRoom/service/ChatRoomService.java
  src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java
  src/main/java/com/ll/TeamSteam/domain/matching/entity/SearchQuery.java
  src/main/java/com/ll/TeamSteam/domain/matching/repository/MatchingRepository.java
  src/main/java/com/ll/TeamSteam/domain/matching/service/MatchingService.java
  src/main/java/com/ll/TeamSteam/domain/matchingPartner/service/MatchingPartnerService.java
  src/main/java/com/ll/TeamSteam/global/init/NotProd.java
  src/main/java/com/ll/TeamSteam/global/rq/Rq.java
  src/main/resources/templates/chat/userList.html
  src/main/resources/templates/common/js.html
  src/main/resources/templates/matching/list.html
Labels: 🎉feature

#107 ref/106 채팅방 URL 입장 시 예외처리
  src/main/java/com/ll/TeamSteam/domain/chatRoom/controller/ChatRoomController.java
  src/main/java/com/ll/TeamSteam/domain/chatRoom/service/ChatRoomService.java
  src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java
  src/main/java/com/ll/TeamSteam/domain/notification/controller/NotificationController.java
  src/main/resources/templates/chat/inviteList.html
Labels: 🛠refactoring

#109 feat/108 페이지 처리 구현
  src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java
  src/main/java/com/ll/TeamSteam/global/init/NotProd.java
  src/main/resources/templates/matching/list.html
Labels: 🎉feature, 🛠refactoring

#111 Test code/110 채팅방 관련 테스트 코드 추가
  src/main/java/com/ll/TeamSteam/domain/chatRoom/service/ChatRoomService.java
  src/main/java/com/ll/TeamSteam/domain/user/entity/User.java
  src/main/java/com/ll/TeamSteam/global/init/NotProd.java
  src/main/resources/templates/common/error.html
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/matching/list.html
  src/main/resources/templates/user/profile.html
  src/test/java/com/ll/TeamSteam/TeamSteamApplicationTests.java
  src/test/java/com/ll/TeamSteam/domain/chatRoom/controller/ChatRoomControllerTest.java
Labels: 📝testcode

#105 feat : RecentlyUser 추가
  src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java
  src/main/java/com/ll/TeamSteam/domain/matchingPartner/repository/MatchingPartnerRepository.java
  src/main/java/com/ll/TeamSteam/domain/matchingPartner/service/MatchingPartnerService.java
  src/main/java/com/ll/TeamSteam/domain/recentlyUser/entity/RecentlyUser.java
  src/main/java/com/ll/TeamSteam/domain/recentlyUser/repository/RecentlyUserRepository.java
  src/main/java/com/ll/TeamSteam/domain/recentlyUser/service/RecentlyUserService.java
  src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java
  src/main/resources/templates/user/profile.html
Labels: 🎉feature

#115 Design/100 상세 페이지 UI 수정
  src/main/java/com/ll/TeamSteam/domain/matching/entity/Matching.java
  src/main/java/com/ll/TeamSteam/domain/matching/service/MatchingService.java
  src/main/java/com/ll/TeamSteam/domain/userTag/UserTag.java
  src/main/java/com/ll/TeamSteam/domain/userTag/gameTag/GameTag.java
  src/main/java/com/ll/TeamSteam/domain/userTag/gameTag/GameTagRepository.java
  src/main/java/com/ll/TeamSteam/global/baseEntity/BaseEntity.java
  src/main/java/com/ll/TeamSteam/global/init/NotProd.java
  src/main/resources/templates/matching/detail.html
  src/main/resources/templates/matching/list.html
Labels: 🎉feature, 🖼design

#116 프로필 페이지, 장르태그 페이지 UI수정, 검증추가
  src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java
  src/main/resources/templates/user/createGenre.html
  src/main/resources/templates/user/profile.html
Labels: 🐞bug, 🖼design

#117 Feature/112 매칭 리스트에 필터링 기능 추가
  src/main/java/com/ll/TeamSteam/domain/chatRoom/service/ChatRoomService.java
  src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java
  src/main/java/com/ll/TeamSteam/domain/matching/entity/GenreTagTypeRequestConverter.java
  src/main/java/com/ll/TeamSteam/domain/matching/entity/Matching.java
  src/main/java/com/ll/TeamSteam/domain/matching/repository/MatchingRepository.java
  src/main/java/com/ll/TeamSteam/domain/matching/service/MatchingService.java
  src/main/java/com/ll/TeamSteam/domain/matchingTag/entity/GenreTagType.java
  src/main/java/com/ll/TeamSteam/global/config/WebConfig.java
  src/main/java/com/ll/TeamSteam/global/init/NotProd.java
  src/main/resources/templates/matching/create.html
  src/main/resources/templates/matching/list.html
Labels: 🎉feature

#118 design : 프로필에서 최근 매칭유저 매너온도 추가
  src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java
  src/main/resources/templates/user/profile.html
Labels: 🎉feature, 🖼design

#119 bug : confilt로 인한 빌드 오류
  src/main/java/com/ll/TeamSteam/global/init/NotProd.java
Labels: 🐞bug

#122 feat/121 필터링 버그 수정 및 기능 추가
  src/main/java/com/ll/TeamSteam/domain/chatRoom/service/ChatRoomService.java
  src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java
  src/main/java/com/ll/TeamSteam/domain/matching/entity/Matching.java
  src/main/java/com/ll/TeamSteam/domain/matching/service/MatchingService.java
  src/main/resources/templates/matching/detail.html
  src/main/resources/templates/matching/modify.html
Labels: 🐞bug, 🎉feature

#125 Feature/124
  src/main/java/com/ll/TeamSteam/domain/miniGame/controller/MinigameController.java
  src/main/java/com/ll/TeamSteam/domain/miniGame/entity/MiniGame.java
  src/main/java/com/ll/TeamSteam/domain/miniGame/repository/MinigameRepository.java
  src/main/java/com/ll/TeamSteam/domain/miniGame/service/MinigameService.java
  src/main/resources/static/minigame/images/ball01.png
  src/main/resources/static/minigame/images/ball02.png
  src/main/resources/static/minigame/images/ball03.png
  src/main/resources/static/minigame/images/character.png
  src/main/resources/static/minigame/images/cur116.cur
  src/main/resources/static/minigame/images/leg.png
  src/main/resources/static/minigame/images/logo.png
  src/main/resources/static/minigame/images/pointer.bmp
  src/main/resources/static/minigame/images/tile_01.png
  src/main/resources/static/minigame/images/tile_05.png
  src/main/resources/static/minigame/js/minigame.js
  src/main/resources/static/minigame/style/minigame.css
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/minigame/CNAME
  src/main/resources/templates/minigame/README.md
  src/main/resources/templates/minigame/images/ball01.png
  src/main/resources/templates/minigame/images/ball02.png
  src/main/resources/templates/minigame/images/ball03.png
  src/main/resources/templates/minigame/images/ball04.png
  src/main/resources/templates/minigame/images/ball06.png
  src/main/resources/templates/minigame/images/character.png
  src/main/resources/templates/minigame/images/character1.png
  src/main/resources/templates/minigame/images/cur116.cur
  src/main/resources/templates/minigame/images/leg.png
  src/main/resources/templates/minigame/images/logo.png
  src/main/resources/templates/minigame/images/pointer.bmp
  src/main/resources/templates/minigame/images/tile_01.png
  src/main/resources/templates/minigame/images/tile_05.png
  src/main/resources/templates/minigame/images/그림4.jpg
  src/main/resources/templates/minigame/index.html
  src/main/resources/templates/minigame/js/main.js
  src/main/resources/templates/minigame/style/main.css
Labels: 🎉feature

#131 bug/130 ChatRoom, Matching 관련 버그 수정
  src/main/java/com/ll/TeamSteam/domain/chatRoom/service/ChatRoomService.java
  src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java
  src/main/java/com/ll/TeamSteam/domain/matching/entity/Matching.java
  src/main/java/com/ll/TeamSteam/domain/matching/repository/MatchingRepository.java
  src/main/java/com/ll/TeamSteam/domain/matching/service/MatchingService.java
  src/main/java/com/ll/TeamSteam/domain/matchingPartner/entity/MatchingPartner.java
  src/main/java/com/ll/TeamSteam/domain/matchingPartner/repository/MatchingPartnerRepository.java
  src/main/java/com/ll/TeamSteam/domain/matchingPartner/service/MatchingPartnerService.java
  src/main/java/com/ll/TeamSteam/domain/matchingTag/entity/GenreTagType.java
  src/main/java/com/ll/TeamSteam/domain/recentlyUser/entity/RecentlyUser.java
  src/main/java/com/ll/TeamSteam/global/init/NotProd.java
  src/main/java/com/ll/TeamSteam/global/rsData/RsData.java
Labels: 🐞bug

#135 bug/134 테스트코드 실패로 젠킨스 빌드 오류
  src/main/java/com/ll/TeamSteam/global/init/NotProd.java
  src/test/java/com/ll/TeamSteam/domain/chatRoom/controller/ChatRoomControllerTest.java
Labels: 🐞bug

#132 Feature/128 페이징처리 및 친구삭제 기능 추가
  src/main/java/com/ll/TeamSteam/domain/friend/repository/FriendRepository.java
  src/main/java/com/ll/TeamSteam/domain/steam/service/SteamService.java
  src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java
  src/main/java/com/ll/TeamSteam/domain/user/service/UserService.java
  src/main/resources/templates/user/createGameTag.html
  src/main/resources/templates/user/profile.html
Labels: 🎉feature, 🖼design

#136 feat/129 명예의전당 페이지 구현
  src/main/java/com/ll/TeamSteam/domain/rank/controller/RankController.java
  src/main/java/com/ll/TeamSteam/domain/rank/service/RankService.java
  src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java
  src/main/java/com/ll/TeamSteam/domain/user/repository/UserRepository.java
  src/main/java/com/ll/TeamSteam/global/init/NotProd.java
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/rank/rank.html
Labels: 🎉feature, 🖼design, 💣conflict

#127 Design/100 메인 페이지, 매칭 목록 및 상세 페이지 UI 수정
  src/main/java/com/ll/TeamSteam/domain/home/HomeController.java
  src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java
  src/main/java/com/ll/TeamSteam/domain/matching/entity/Matching.java
  src/main/java/com/ll/TeamSteam/domain/matching/service/MatchingService.java
  src/main/java/com/ll/TeamSteam/global/init/NotProd.java
  src/main/resources/templates/main/home.html
  src/main/resources/templates/matching/detail.html
  src/main/resources/templates/matching/list.html
Labels: 🎉feature, 🖼design

#139 feat/138 채팅방 owner는 나가기 못하도록 설정
  src/main/java/com/ll/TeamSteam/domain/chatRoom/service/ChatRoomService.java
  src/main/resources/templates/chat/room.html
Labels: 🐞bug, 🎉feature

#140 ref/141 miniGame에 layout 적용
  src/main/java/com/ll/TeamSteam/domain/miniGame/controller/MiniGameController.java
  src/main/java/com/ll/TeamSteam/domain/miniGame/controller/MinigameController.java
  src/main/java/com/ll/TeamSteam/domain/miniGame/entity/MiniGame.java
  src/main/java/com/ll/TeamSteam/domain/miniGame/repository/MiniGameRepository.java
  src/main/java/com/ll/TeamSteam/domain/miniGame/service/MiniGameService.java
  src/main/resources/static/minigame/images/logo.png
  src/main/resources/static/minigame/style/minigame.css
  src/main/resources/templates/minigame/CNAME
  src/main/resources/templates/minigame/README.md
  src/main/resources/templates/minigame/images/ball01.png
  src/main/resources/templates/minigame/images/ball02.png
  src/main/resources/templates/minigame/images/ball03.png
  src/main/resources/templates/minigame/images/ball04.png
  src/main/resources/templates/minigame/images/ball06.png
  src/main/resources/templates/minigame/images/character.png
  src/main/resources/templates/minigame/images/character1.png
  src/main/resources/templates/minigame/images/cur116.cur
  src/main/resources/templates/minigame/images/leg.png
  src/main/resources/templates/minigame/images/logo.png
  src/main/resources/templates/minigame/images/pointer.bmp
  src/main/resources/templates/minigame/images/tile_01.png
  src/main/resources/templates/minigame/images/tile_05.png
  src/main/resources/templates/minigame/images/그림4.jpg
  src/main/resources/templates/minigame/index.html
  src/main/resources/templates/minigame/js/main.js
  src/main/resources/templates/minigame/style/main.css
Labels: 🛠refactoring

#142 Feature/137 메인 페이지에 정렬 기능 추가
  src/main/java/com/ll/TeamSteam/domain/home/HomeController.java
  src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java
  src/main/java/com/ll/TeamSteam/domain/matching/entity/Matching.java
  src/main/java/com/ll/TeamSteam/domain/matching/service/MatchingService.java
  src/main/resources/templates/main/home.html
Labels: 🎉feature, 🖼design

#143 bug/144 testCode 버그 잠시 주석
  src/test/java/com/ll/TeamSteam/domain/chatRoom/controller/ChatRoomControllerTest.java
Labels: 🐞bug

#148 feat/147 로그인한 유저의 avatar 받아오기
  src/main/java/com/ll/TeamSteam/domain/miniGame/controller/MiniGameController.java
  src/main/java/com/ll/TeamSteam/domain/miniGame/dto/ScoreRequest.java
  src/main/java/com/ll/TeamSteam/domain/miniGame/entity/MiniGame.java
  src/main/java/com/ll/TeamSteam/domain/miniGame/repository/MiniGameRepository.java
  src/main/java/com/ll/TeamSteam/domain/miniGame/service/MiniGameService.java
  src/main/resources/static/minigame/js/minigame.js
  src/main/resources/static/minigame/style/minigame.css
  src/main/resources/templates/minigame/index.html
Labels: 🎉feature, 🖼design

#149 Bug/133 UI 수정, 버그 수정
  src/main/java/com/ll/TeamSteam/domain/chatRoom/controller/ChatRoomController.java
  src/main/java/com/ll/TeamSteam/domain/chatRoom/service/ChatRoomService.java
  src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java
  src/main/java/com/ll/TeamSteam/domain/user/service/UserService.java
  src/main/resources/templates/user/createGameTag.html
  src/main/resources/templates/user/createGenre.html
  src/main/resources/templates/user/isLogin.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/profile.html
Labels: 🐞bug, 🖼design

#150 Feature/137 메인 페이지에 정렬 기능 추가 및 마감 시간 로직 처리
  src/main/java/com/ll/TeamSteam/domain/matching/entity/Matching.java
  src/main/java/com/ll/TeamSteam/domain/matching/service/MatchingService.java
  src/main/resources/templates/matching/detail.html
Labels: 🎉feature, 🖼design

#153 design/152 leg 삭제, 1,2,3등은 트로피 모양으로 출력
  src/main/resources/static/minigame/images/character.png
  src/main/resources/static/minigame/images/leg.png
  src/main/resources/static/minigame/style/minigame.css
  src/main/resources/templates/minigame/index.html
Labels: 🖼design

#158 feat/157 부정적인 생성 시 error페이지로 이동
  src/main/java/com/ll/TeamSteam/domain/home/HomeController.java
  src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java
  src/main/java/com/ll/TeamSteam/domain/matching/exception/MatchingPartnerNotFoundException.java
  src/main/java/com/ll/TeamSteam/global/error/GlobalExceptionHandler.java
Labels: 🎉feature

#160 Feature/156 매칭 수정 시 마감 시간 변경 기능 구현
  src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java
  src/main/java/com/ll/TeamSteam/domain/matching/entity/Matching.java
  src/main/java/com/ll/TeamSteam/domain/matching/service/MatchingService.java
  src/main/resources/templates/matching/create.html
  src/main/resources/templates/matching/modify.html
Labels: 🎉feature

#162 명예의전당 UI수정
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/minigame/index.html
  src/main/resources/templates/rank/rank.html
Labels: 🛠refactoring, 🖼design

#163 Design/151
  src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java
  src/main/resources/templates/error/400.html
  src/main/resources/templates/error/403.html
  src/main/resources/templates/error/404.html
  src/main/resources/templates/error/500.html
  src/main/resources/templates/user/profile.html
Labels: 🎉feature, 🖼design

#167 Feature/164 메인 페이지 기능 추가 및 매칭 목록, 상세 페이지 UI 수정
  src/main/resources/templates/main/home.html
  src/main/resources/templates/matching/detail.html
  src/main/resources/templates/matching/list.html
Labels: 🎉feature, 🖼design

#173 bug/172 방이 존재하지 않을 경우 noChatroomError가 나오도록
  src/main/java/com/ll/TeamSteam/domain/chatRoom/controller/ChatRoomController.java
  src/main/java/com/ll/TeamSteam/domain/chatRoom/exception/NoChatRoomException.java
  src/main/java/com/ll/TeamSteam/domain/chatRoom/service/ChatRoomService.java
  src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java
  src/main/java/com/ll/TeamSteam/domain/matchingPartner/service/MatchingPartnerService.java
  src/main/java/com/ll/TeamSteam/global/error/GlobalExceptionHandler.java
  src/main/resources/templates/error/noChatroomError.html
Labels: 🐞bug, 🛠refactoring

#176 Design/171 매칭 상세 UI 수정
  src/main/java/com/ll/TeamSteam/domain/matching/entity/Matching.java
  src/main/resources/templates/matching/detail.html
Labels: 🖼design

#177 Refactoring/170 매칭글 Valid 적용으로 게시글 검증, 마감시간 무관 추가
  src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java
  src/main/java/com/ll/TeamSteam/domain/matching/entity/Matching.java
  src/main/java/com/ll/TeamSteam/domain/matching/service/MatchingService.java
  src/main/java/com/ll/TeamSteam/global/init/NotProd.java
  src/main/resources/templates/matching/create.html
  src/main/resources/templates/matching/list.html
Labels: 🛠refactoring, 🖼design

#175 Design/169 UI,버그 수정
  src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java
  src/main/resources/templates/chat/inviteList.html
  src/main/resources/templates/chat/room.html
  src/main/resources/templates/chat/userList.html
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/matching/detail.html
  src/main/resources/templates/notification/list.html
  src/main/resources/templates/user/createGameTag.html
  src/main/resources/templates/user/createGenre.html
  src/main/resources/templates/user/profile.html
Labels: 🐞bug, 🖼design

#181 ref/180 createForm 검증 로직, 글자 수 제한
  src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java
  src/main/resources/templates/main/home.html
  src/main/resources/templates/matching/create.html
  src/main/resources/templates/matching/detail.html
  src/main/resources/templates/matching/list.html
Labels: 🛠refactoring, 🖼design

#182 bug/183 방장은 매칭 생성 시 COMMON 타입
  src/main/java/com/ll/TeamSteam/domain/chatRoom/service/ChatRoomService.java
Labels: 🐞bug

#187 Refactoring/186 modify.html, detail.html, 타이틀명 수정
  src/main/resources/templates/matching/create.html
  src/main/resources/templates/matching/detail.html
  src/main/resources/templates/matching/modify.html
  src/main/resources/templates/rank/rank.html
  src/main/resources/templates/user/createGenre.html
  src/main/resources/templates/user/login.html
Labels: 🛠refactoring, 🖼design

#190 design : 프로필가는버튼
  src/main/resources/templates/user/profile.html
Labels: 🖼design

#191 Bug/188 미니 프로필 버그 수정 및 자잘한 버그 수정
  src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java
  src/main/resources/templates/matching/detail.html
  src/main/resources/templates/matching/modify.html
Labels: 🐞bug

#193 Bug/192 추가 버그 수정
  src/main/java/com/ll/TeamSteam/domain/matching/service/MatchingService.java
  src/main/java/com/ll/TeamSteam/domain/matchingTag/entity/GenreTagType.java
  src/main/java/com/ll/TeamSteam/domain/userTag/gameTag/GameTagRepository.java
  src/main/resources/templates/common/layout.html
Labels: 🐞bug

#198 ref/195 Query Dsl 적용
  .gitignore
  build.gradle
  spy.log
  src/main/generated/com/ll/TeamSteam/domain/chatMessage/entity/QChatMessage.java
  src/main/generated/com/ll/TeamSteam/domain/chatRoom/entity/QChatRoom.java
  src/main/generated/com/ll/TeamSteam/domain/chatUser/entity/QChatUser.java
  src/main/generated/com/ll/TeamSteam/domain/friend/entity/QFriend.java
  src/main/generated/com/ll/TeamSteam/domain/matching/entity/QMatching.java
  src/main/generated/com/ll/TeamSteam/domain/matchingPartner/entity/QMatchingPartner.java
  src/main/generated/com/ll/TeamSteam/domain/matchingTag/entity/QMatchingTag.java
  src/main/generated/com/ll/TeamSteam/domain/miniGame/entity/QMiniGame.java
  src/main/generated/com/ll/TeamSteam/domain/notification/entity/QNotification.java
  src/main/generated/com/ll/TeamSteam/domain/recentlyUser/entity/QRecentlyUser.java
  src/main/generated/com/ll/TeamSteam/domain/steam/entity/QSteamGameLibrary.java
  src/main/generated/com/ll/TeamSteam/domain/user/entity/QUser.java
  src/main/generated/com/ll/TeamSteam/domain/userTag/QUserTag.java
  src/main/generated/com/ll/TeamSteam/domain/userTag/gameTag/QGameTag.java
  src/main/generated/com/ll/TeamSteam/domain/userTag/genreTag/QGenreTag.java
  src/main/generated/com/ll/TeamSteam/global/baseEntity/QBaseEntity.java
  src/main/java/com/ll/TeamSteam/domain/chatMessage/controller/ChatMessageController.java
  src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java
  src/main/java/com/ll/TeamSteam/domain/matching/repository/MatchingRepository.java
  src/main/java/com/ll/TeamSteam/domain/matching/repository/MatchingRepositoryCustom.java
  src/main/java/com/ll/TeamSteam/domain/matching/repository/MatchingRepositoryImpl.java
  src/main/java/com/ll/TeamSteam/domain/matching/service/MatchingService.java
  src/main/java/com/ll/TeamSteam/global/config/QueryDSLConfiguration.java
Labels: 🛠refactoring

#203 Refactoring/201 메서드명 수정, 메서드 분리
  src/main/java/com/ll/TeamSteam/domain/chatMessage/controller/ChatMessageController.java
  src/main/java/com/ll/TeamSteam/domain/chatMessage/service/ChatMessageService.java
  src/main/java/com/ll/TeamSteam/domain/chatRoom/controller/ChatRoomController.java
  src/main/java/com/ll/TeamSteam/domain/chatRoom/entity/ChatRoom.java
  src/main/java/com/ll/TeamSteam/domain/chatRoom/service/ChatRoomService.java
  src/main/java/com/ll/TeamSteam/domain/chatUser/service/ChatUserService.java
  src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java
  src/main/java/com/ll/TeamSteam/domain/matchingPartner/service/MatchingPartnerService.java
  src/main/java/com/ll/TeamSteam/global/init/NotProd.java
  src/main/resources/templates/chat/rooms.html
  src/test/java/com/ll/TeamSteam/domain/chatRoom/controller/ChatRoomControllerTest.java
Labels: 🛠refactoring

#205 Refactoring/204
  src/main/java/com/ll/TeamSteam/domain/chatMessage/controller/ChatMessageController.java
  src/main/java/com/ll/TeamSteam/domain/chatMessage/service/ChatMessageService.java
  src/main/java/com/ll/TeamSteam/domain/chatRoom/controller/ChatRoomController.java
  src/main/java/com/ll/TeamSteam/domain/chatRoom/dto/ChatRoomDto.java
  src/main/java/com/ll/TeamSteam/domain/chatRoom/exception/CanNotEnterException.java
  src/main/java/com/ll/TeamSteam/domain/chatRoom/exception/NotInChatRoomException.java
  src/main/java/com/ll/TeamSteam/domain/chatRoom/service/ChatRoomService.java
  src/main/java/com/ll/TeamSteam/domain/chatUser/service/ChatUserService.java
  src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java
  src/main/java/com/ll/TeamSteam/domain/matching/entity/GenreTagTypeRequestConverter.java
  src/main/java/com/ll/TeamSteam/domain/notification/controller/NotificationController.java
  src/main/java/com/ll/TeamSteam/global/config/WebConfig.java
  src/main/java/com/ll/TeamSteam/global/error/GlobalExceptionHandler.java
  src/main/java/com/ll/TeamSteam/standard/util/Ut.java
  src/main/resources/static/app.js
  src/main/resources/templates/error/canNotEnterChatRoom.html
  src/main/resources/templates/error/notInChatRoom.html
  src/main/resources/templates/matching/detail.html
Labels: 🛠refactoring

#206 testCode : Chat관련 테스트 코드 작성
  src/main/java/com/ll/TeamSteam/global/init/NotProd.java
  src/test/java/com/ll/TeamSteam/domain/chatRoom/controller/ChatRoomControllerTest.java
Labels: 📝testcode

#202 Ref/196
  build.gradle
  src/main/generated/com/ll/TeamSteam/domain/gameTag/entity/QGameTag.java
  src/main/generated/com/ll/TeamSteam/domain/genreTag/entity/QGenreTag.java
  src/main/generated/com/ll/TeamSteam/domain/user/entity/QUser.java
  src/main/generated/com/ll/TeamSteam/domain/userTag/entity/QUserTag.java
  src/main/java/com/ll/TeamSteam/domain/friend/service/FriendService.java
  src/main/java/com/ll/TeamSteam/domain/gameTag/entity/GameTag.java
  src/main/java/com/ll/TeamSteam/domain/gameTag/repository/GameTagRepository.java
  src/main/java/com/ll/TeamSteam/domain/gameTag/service/GameTagService.java
  src/main/java/com/ll/TeamSteam/domain/genreTag/entity/GenreTag.java
  src/main/java/com/ll/TeamSteam/domain/genreTag/repository/GenreTagRepository.java
  src/main/java/com/ll/TeamSteam/domain/genreTag/service/GenreTagService.java
  src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java
  src/main/java/com/ll/TeamSteam/domain/matching/entity/Matching.java
  src/main/java/com/ll/TeamSteam/domain/matching/service/MatchingService.java
  src/main/java/com/ll/TeamSteam/domain/matchingPartner/entity/MatchingPartner.java
  src/main/java/com/ll/TeamSteam/domain/matchingPartner/service/MatchingPartnerService.java
  src/main/java/com/ll/TeamSteam/domain/recentlyUser/entity/RecentlyUser.java
  src/main/java/com/ll/TeamSteam/domain/recentlyUser/service/RecentlyUserService.java
  src/main/java/com/ll/TeamSteam/domain/steam/entity/SteamGameLibrary.java
  src/main/java/com/ll/TeamSteam/domain/steam/service/SteamGameLibraryService.java
  src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java
  src/main/java/com/ll/TeamSteam/domain/user/entity/User.java
  src/main/java/com/ll/TeamSteam/domain/user/service/UserService.java
  src/main/java/com/ll/TeamSteam/domain/userTag/entity/UserTag.java
  src/main/java/com/ll/TeamSteam/domain/userTag/repository/UserTagRepository.java
  src/main/java/com/ll/TeamSteam/domain/userTag/service/UserTagService.java
  src/main/java/com/ll/TeamSteam/global/init/NotProd.java
  src/main/java/com/ll/TeamSteam/global/security/SecurityConfig.java
  src/main/java/com/ll/TeamSteam/global/security/UserInfoResponse.java
  src/test/java/com/ll/TeamSteam/domain/recentlyUser/service/RecentlyUserServiceTest.java
  src/test/java/com/ll/TeamSteam/domain/user/service/UserServiceTest.java
Labels: 🛠refactoring, 📝testcode
